language: python
python:
    - "3.5"
    - "3.6"
cache: pip
install:
    - pip install -r requirements.txt
before_script:
    # Something
script:
    # - python tests.py
    - py.test tests/tests.py --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing

after_success:
    - coveralls
